# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "integration plus v1"
client_id = "ff3b941e8550ebdf118f88c3cb1c269c"
application_url = "https://revenue-traditional-aircraft-chevy.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://revenue-traditional-aircraft-chevy.trycloudflare.com/auth/callback",
  "https://revenue-traditional-aircraft-chevy.trycloudflare.com/auth/shopify/callback",
  "https://revenue-traditional-aircraft-chevy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "codechallangev1.myshopify.com"
